/**
 * The XHTTP `extra=` payload, mirroring `model.Transport.XHTTPExtra()`.
 *
 * Modern XHTTP has far more knobs than a link can carry as individual query
 * parameters, so the surplus rides as one JSON blob under `extra=`. That is the
 * shape the clients and the other panels already read, and it is what makes the
 * link lossless: without it a node re-imported from its own link comes back with
 * its CDN tuning silently reset to defaults.
 *
 * Byte equality with Go is the requirement, not merely equivalent JSON. Go
 * marshals a struct with `omitempty`, which drops zero values and sorts nothing
 * — but the nested xmux/download objects are `map[string]any`, which Go DOES
 * sort. goMarshal reproduces both behaviours, so this file must build the same
 * objects with the same omissions and hand them to goMarshal rather than
 * JSON.stringify. testdata/golden.json is generated by the real Go exporters and
 * fails this file the moment the two disagree.
 */

import type { Transport, XMux } from '../model/node';
import { goMarshal, type JSONValue } from './gojson';

/** `model.xmuxWire` — only the keys the pinned core actually parses. */
function xmuxWire(x: XMux): Record<string, JSONValue> {
  const m: Record<string, JSONValue> = {};
  if (x.max_concurrency) m.maxConcurrency = x.max_concurrency;
  if (x.max_connections) m.maxConnections = x.max_connections;
  if (x.c_max_reuse_times) m.cMaxReuseTimes = x.c_max_reuse_times;
  if (x.h_max_request_times) m.hMaxRequestTimes = x.h_max_request_times;
  if (x.h_max_reusable_secs) m.hMaxReusableSecs = x.h_max_reusable_secs;
  if ((x.h_keep_alive_period ?? 0) > 0) m.hKeepAlivePeriod = x.h_keep_alive_period!;
  return m;
}

/**
 * Build the extra object for a transport. Keys and omission rules mirror
 * `xhttpExtra`'s json tags exactly; an extra key here, or a missing omitempty,
 * is a different link.
 */
function extraObject(t: Transport): Record<string, JSONValue> {
  const e: Record<string, JSONValue> = {};
  if (t.x_padding_bytes) e.xPaddingBytes = t.x_padding_bytes;
  if (t.x_padding_obfs_mode) e.xPaddingObfsMode = true;
  if (t.x_padding_key) e.xPaddingKey = t.x_padding_key;
  if (t.x_padding_header) e.xPaddingHeader = t.x_padding_header;
  if (t.x_padding_placement) e.xPaddingPlacement = t.x_padding_placement;
  if (t.x_padding_method) e.xPaddingMethod = t.x_padding_method;
  if (t.no_grpc_header) e.noGRPCHeader = true;
  if (t.no_sse_header) e.noSSEHeader = true;
  if (t.sc_max_each_post_bytes) e.scMaxEachPostBytes = t.sc_max_each_post_bytes;
  if (t.sc_min_posts_interval_ms) e.scMinPostsIntervalMs = t.sc_min_posts_interval_ms;
  if (t.session_placement) e.sessionPlacement = t.session_placement;
  if (t.session_key) e.sessionKey = t.session_key;
  if (t.seq_placement) e.seqPlacement = t.seq_placement;
  if (t.seq_key) e.seqKey = t.seq_key;
  if (t.uplink_data_placement) e.uplinkDataPlacement = t.uplink_data_placement;
  if (t.uplink_data_key) e.uplinkDataKey = t.uplink_data_key;
  if (t.uplink_http_method) e.uplinkHTTPMethod = t.uplink_http_method;
  if ((t.uplink_chunk_size ?? 0) > 0) e.uplinkChunkSize = t.uplink_chunk_size!;
  if (t.headers && Object.keys(t.headers).length > 0) {
    e.headers = t.headers as Record<string, JSONValue>;
  }
  if (t.xmux) {
    const m = xmuxWire(t.xmux);
    // Go marshals the xmux map unconditionally once XMux is non-nil, and an
    // empty map serialises as {}. Matching that exactly matters: emitting
    // nothing where Go emits {} is a different link.
    e.xmux = m;
  }
  return e;
}

/**
 * The `extra=` value for an XHTTP transport, or '' when there is nothing to
 * carry. Non-XHTTP transports never produce one.
 */
export function xhttpExtra(t: Transport): string {
  if (t.network !== 'xhttp') return '';
  const e = extraObject(t);
  if (Object.keys(e).length === 0) return '';
  const raw = goMarshal(e as JSONValue);
  return raw === '{}' ? '' : raw;
}
