#!/usr/bin/env bash
# Sync the third-party-host distribution (paranoideveloper/forgepanel-3rdp).
#
# The mirror is a separate repository, not a branch, so this is a copy with
# deliberate omissions. Two things about it have already gone wrong once each,
# and both are encoded here rather than left to be remembered:
#
#   1. EVERY root-only exclude is anchored with a leading slash. An rsync
#      pattern without one matches at every depth, so a bare `Dockerfile` meant
#      to skip the root one also skipped deploy/paas/Dockerfile — and a fix
#      committed upstream never reached the deploy for weeks.
#
#   2. The mirror gets a ROOT Dockerfile, generated here from the PaaS one.
#      Render detects a Dockerfile at the repository root and pre-selects the
#      Docker runtime; with none it falls back to language detection, runs
#      `go build` at the root, and fails with "no Go files" — which is what it
#      did. Generating it means the two cannot drift.
set -euo pipefail

SRC=${SRC:-/home/ubuntu/forgepanel-clean}
DST=${DST:-/home/ubuntu/forgepanel-3rdp}

if [[ ! -d "$SRC/.git" || ! -d "$DST/.git" ]]; then
  echo "sync-3rdp: $SRC and $DST must both be git checkouts" >&2
  exit 2
fi

EXCLUDES=$(mktemp)
trap 'rm -f "$EXCLUDES"' EXIT
cat > "$EXCLUDES" <<'EOF'
.git/
/.github/
/.goreleaser.yaml
/AGENTS.md
/CHANGELOG.md
/Dockerfile
/RELEASE_NOTES.md
/STATE.md
/docker-compose.yml
/install.sh
/install.sh.sha256
/forgenode
/README.md
/Makefile
/.env.example
/cmd/forgeedge-bot/
/cmd/forgectl/install_script_test.go
/cmd/forgectl/install_timesync_test.go
/deploy/cloudflare/
/deploy/install.sh
/docs/DNS_WIZARD.md
/docs/E2E_REPORT.md
/docs/EDGE_BOT.md
/docs/FORGEDNS.md
/docs/INSTALL.md
/docs/LICENSING.md
/docs/UI_AUDIT.md
/e2e/
/packaging/
/scripts/
/test/
/tools/
/internal/edgebot/
frontend/node_modules
frontend/.svelte-kit/
frontend/build/
frontend/coverage/
EOF

rsync -a --delete --exclude-from="$EXCLUDES" "$SRC/" "$DST/"

# The root Dockerfile every platform autodetects. Generated, never edited: the
# PaaS Dockerfile is the source, and the manifests reference it by its real path
# so all four routes build the same image.
# The syntax directive has to stay the FIRST line of the file or BuildKit reads
# it as an ordinary comment and silently uses the default frontend, so the
# generated header goes after it rather than above it.
{
  head -n 1 "$SRC/deploy/paas/Dockerfile" | grep -q '^# syntax=' \
    && head -n 1 "$SRC/deploy/paas/Dockerfile"
  echo "# GENERATED by scripts/sync-3rdp.sh from deploy/paas/Dockerfile — do not edit."
  echo "#"
  echo "# It exists at the root because that is where Render looks when deciding"
  echo "# whether a repository is a Docker service at all. Without it Render picks a"
  echo "# native Go runtime, runs 'go build' at the root, and fails with 'no Go files'"
  echo "# — this panel's Go sources are all under cmd/ and internal/, and it needs bun"
  echo "# for the frontend and the cores baked in besides, so no native runtime can"
  echo "# build it."
  echo "#"
  if head -n 1 "$SRC/deploy/paas/Dockerfile" | grep -q '^# syntax='; then
    tail -n +2 "$SRC/deploy/paas/Dockerfile"
  else
    cat "$SRC/deploy/paas/Dockerfile"
  fi
} > "$DST/Dockerfile"

echo "synced $SRC -> $DST"
echo "root Dockerfile generated from deploy/paas/Dockerfile ($(wc -l < "$DST/Dockerfile") lines)"
